### ISSUE TITLE
New EaselJS version

### ISSUE THREAD

**Issue by Richard-Walton** [Fintan/easelhx#1]
Hello there,

Do you have any plans to update the externs for the latest version of Easel (6.0.1) which was released recently?

Thanks,
Richard.

**Comment by Fintan** [comment]
Hi Richard,

I don't have any immediate plans to update to 6.0.1 due to limited time.  If you are interested in having a go yourself you can use https://github.com/Fintan/buildhx to automatically generate the externs because Createjs has YUI Doc style code comments that buildhx supports .  Some manual alterations will then be required but it handles the majority of the work. 

Fintan
